### PR TITLE
feature: suppor get  Attribute

### PR DESCRIPTION
**Pull request by cq-z**

### CODE REVIEW

**Comment by cq-z** [comment]
@nitram509 this feature is ok？

**Comment by nitram509** [comment]
@cq-z 
Hi Hugh,
apologies for my late reply, I did relocate and had just a little spare time.

About this feature, may I ask what problem you try to solve?
At the moment I struggle to see the value here 🤷 

About your implementation, I don't want to mix the BPMN structs/interfaces with xml.Attributes
That will surely result in headaches later when I plan to implement serializing the model to disc.

But before talking further about what to change in the implementation, please lets clarify your use case first.

**Comment by cq-z** [comment]
hi Martin，
Sometimes you need to set some custom configuration into the xml when setting up the process。or callback func parameter

**Comment by nitram509** [comment]
Well, I'm still not getting it yet, why use arbitrary XML attributes for that?
Wouldn't it be more convenient to use existing possibilities, like setting variables in the input or output section of a task?

See this example for explicit and implicit initialization values...
Screenshot 2023-02-08 at 12 10 11
Screenshot 2023-02-08 at 12 10 20

**Comment by cq-z** [comment]
It's my fault
It's only right：
image

**Comment by nitram509** [comment]
You're welcome :)

**Pull request closed without merging**
